name: Web publisher
on:
  push:
    branches:
      - main
jobs:
  web-publisher:
    name: Web publisher
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          path: "/basic",
          project-file: "basic.atta"
        }
        
    steps:
        # Clone project 
      - uses: actions/checkout@v3
        # Clone atta
      - uses: actions/checkout@v3
        with:
          repository: brenocq/atta
          ref: publish-project
          path: atta
        # Setup emscripten
      - uses: mymindstorm/setup-emsdk@v9

        # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake assimp-utils libbullet-dev
          cmake --version
          gcc --version

        # Google Storage setup 
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

        # Project web build
      - name: Build and update basic.atta
        working-directory: atta
        run: |
          ./scripts/build.sh --type web_module --static /home/runner/work/boids/boids${{matrix.path}}/${{matrix.project-file}}
          gsutil cp build/bin/* gs://${{secrets.GCP_PATH}}${{matrix.path}}/
