name: Web publisher
on:
  push:
    branches:
      - main
jobs:
  web-publisher:
    name: Web publisher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Google Storage setup 
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
   
      - name: Use gcloud CLI
        run: gcloud info

        # Clone atta and build web
      - name: Clone Atta and build web build
        uses: actions/checkout@v3
        with:
          repository: brenocq/atta
          ref: publish-project
        run: |
          pwd
          ls .

      - name: Build web build
        run: |
          pwd
          ls .

        # Update Google Storage
      - name: Update Google Storage
        run: echo 'Update google storage'
