name: Web publisher
on:
  push:
    branches:
      - main
jobs:
  web-publisher:
    name: Web publisher
    runs-on: ubuntu-latest
    steps:
        # Clone project 
      - uses: actions/checkout@v3
        # Clone atta
      - uses: actions/checkout@v3
        with:
          repository: brenocq/atta
          ref: publish-project
          path: atta

        # Google Storage setup 
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
   
      - name: Use gcloud CLI
        run: gcloud info

        # Project web build
      - name: Build web build
        working-directory: atta
        run: |
          pwd
          ls
          ./scripts/build.sh -h
          ./scripts/build.sh --type web_module --static /home/runner/work/boids/boids/basic/basic.atta
          ls bin

        # Update Google Storage
      - name: Update Google Storage
        run: echo 'Update google storage'
